### ISSUE TITLE
clear timeout 

### ISSUE THREAD

**Issue by KoopReynders** [DivaniNL/ui-events#2]
Je kan een timeout methode ook stoppen. Dat zou je kunnen doen als een gebruiker stopt met de longpress, dan loopt de timer niet door...

Hier staat het uitgelegd: https://developer.mozilla.org/en-US/docs/Web/API/Window/setTimeout

Darin staat ook het 'this probleem' uitgelegd
https://developer.mozilla.org/en-US/docs/Web/API/Window/setTimeout#the_this_problem

https://github.com/DivaniNL/ui-events/blob/7e3f9aeca703cb82f32d2553eae27421c4afd018/main.js#L151-L154

**Comment by DivaniNL** [comment]
[fixed timer on long press part 1](https://github.com/DivaniNL/ui-events/commit/44947ab1ec6a22f995cc35636cce220522aa36ff/)

[fixed timer on long press part 2](https://github.com/DivaniNL/ui-events/commit/1c67d151a379389157d449178d0aaa9846d6dc65)
